# Generated by Django 5.0.6 on 2024-10-26 02:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulasan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
