# Generated by Django 5.1.2 on 2024-10-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_post_comment_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='thread',
            new_name='post',
        ),
    ]
