# Generated by Django 5.1.2 on 2024-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='status',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('Kartu Kredit', 'Kartu Kredit'), ('Kartu Debit', 'Kartu Debit'), ('Transfer Bank', 'Transfer Bank'), ('E-Wallet', 'E-Wallet')], max_length=100),
        ),
    ]
