# Generated by Django 5.1.2 on 2024-10-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0002_remove_pembayaran_status_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='payment_method',
            field=models.CharField(choices=[('Kartu Kredit', 'Kartu Kredit'), ('Kartu Debit', 'Kartu Debit'), ('Transfer Bank', 'Transfer Bank'), ('E-Wallet', 'E-Wallet')], max_length=100),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
