# Generated by Django 5.0.6 on 2024-10-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_produk_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produk',
            new_name='Product',
        ),
    ]
