# Generated by Django 5.1.2 on 2024-10-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_produk_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.CharField(choices=[('Dasi Instant', 'Dasi Instant'), ('Dasi Manual', 'Dasi Manual'), ('Dasi Kupu-Kupu', 'Dasi Kupu-Kupu'), ('Jepitan Dasi', 'Jepitan Dasi')], max_length=255),
        ),
    ]
