# Generated by Django 5.1.2 on 2024-10-26 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('Jakarta Barat', 'Jakarta Barat'), ('Jakarta Pusat', 'Jakarta Pusat'), ('Jakarta Selatan', 'Jakarta Selatan'), ('Jakarta Timur', 'Jakarta Timur'), ('Jakarta Utara', 'Jakarta Utara')], max_length=100)),
                ('postal_code', models.IntegerField()),
                ('courier', models.CharField(choices=[('JNE', 'JNE'), ('SICEPAT', 'SiCepat'), ('GOJEK', 'Gojek'), ('GRAB', 'Grab')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
