# Generated by Django 5.1.2 on 2024-10-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengiriman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengiriman',
            name='address',
            field=models.TextField(),
        ),
    ]
